Sat Nov  5 12:10:11 AM WIB 2022

diff --git a/alpine b/alpine
--- a/alpine
+++ b/alpine
@@ -78,8 +78,10 @@ __usage__ () {
 	printf "	$(basename $0) [options]\n"
 	printf "\n"
 	printf "Options:\n"
-	printf "	--login			login to linux alpine mini rootfs.\n"
-	printf " -v,	--version		show alpine linux version info.\n"
+	printf "	--install		install alpine rootfs.\n"
+	printf "	--reset			reset alpine rootfs.\n"
+	printf "	--login			login to Alpine Linu rootfs.\n"
+	printf " -v,	--version		show Alpine Linux version info.\n"
 	printf " -h,	--help			show help information.\n"
 	printf "\n"
 	return 1
@@ -176,6 +178,42 @@ __install__ () {
 			echo 'PS1="\W \\$ "' >> $tmp/profile
 			echo 'cd $HOME' >> $tmp/profile
 			sudo cp $tmp/profile $root/etc/profile
+		fi
+	else
+		latest_releases=$(curl -s $rel_url -o $dir/$rel-releases.yaml --connect-timeout 10)
+		if [ -f $dir/$rel-releases.yaml ]; then
+			version=$(cat $dir/$rel-releases.yaml | grep -m 1 -o version.* | sed -e 's/[^0-9.]*//g' -e 's/-$//')
+			rootfs="alpine-minirootfs-${version}-${arch}.tar.gz"
+			url_rootfs=$url/alpine/$rel/releases/$arch/$rootfs
+			rootfs_file=$dir/$rootfs
+			if [ ! -f $dir/$rootfs ]; then
+				curl --progress-bar -L --fail --retry 4 $url_rootfs -o $rootfs_file || {
+					printf "installation aborted.\n"
+					exit 1
+				}
+			fi
+			tar -xf $rootfs_file -C $root || {
+				printf "extract: error: $rootfs corrupted."
+				rm -rf $rootfs_file
+				printf "installation aborted.\n"
+				exit 1
+			}
+			cp $root/etc/apk/repositories $root/etc/apk/repositories.bak
+			rm -rf $tmp/repositories
+			printf "https://dl-cdn.alpinelinux.org/alpine/$rel/main/\n" > $tmp/repositories
+			printf "https://dl-cdn.alpinelinux.org/alpine/$rel/community/\n" >> $tmp/repositories
+			if [ $rel = "edge" ]; then
+				printf "https://dl-cdn.alpinelinux.org/alpine/edge/testing/\n" >> $tmp/repositories
+			fi
+			cp $tmp/repositories $root/etc/apk/repositories
+			rm -rf $tmp/resolv
+			printf "nameserver 1.1.1.1" > $tmp/resolv 
+			cp $tmp/resolv $root/etc/resolv.conf
+			rm -rf $tmp/profile
+			cat $root/etc/profile > $tmp/profile
+			echo 'PS1="\W \\$ "' >> $tmp/profile
+			echo 'cd $HOME' >> $tmp/profile
+			cp $tmp/profile $root/etc/profile
 		fi
 	fi
 	return 1
